### PR TITLE
feat: add `to_title` helper func

### LINKED ISSUE #51: Add `to_title` helper function
### Please describe your feature request:
It would be useful to add the following helpers:

to_proper(input string) string | Transforms the input into ProperCase characters | to_proper("hello") | Hello

### Describe the use case of this feature:
 Would be Useful for Fuzzing filenames/Usernames

### PR DESCRIPTION
**Pull request by dwisiswant0**
Close #51

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]
Future proposal: what do you think about a unique function for languages formatting, accepting multiple optional arguments, something like:

```
format("string", "language", title | lower | upper | camel_case | snake_case | ...)
```

**Comment by dwisiswant0** [comment]
> Future proposal: what do you think about a unique function for languages formatting, accepting multiple optional arguments, something like:
> 
> ```
> format("string", "language", title | lower | upper | camel_case | snake_case | ...)
> ```

I prefer having these "case converter" funcs as separate DSLs so they can be chained with other converters<sup>[?]</sup>, like `to_slug(to_title())`, instead of `convert_case(s, caseType)` or the `format` func you proposed.

https://github.com/chanced/caps

**Comment by dwisiswant0** [comment]
Unless `caseType(s)` is variadic, then converts based on index, I'm on board with that.

**Comment by dwisiswant0** [comment]
Can we merge it, @ehsandeep?

**Pull request merged**
